### ISSUE TITLE
Trying to understand the training of PG-GAN on LSUN dataset with class labels

### ISSUE THREAD

**Issue by prash030** [aleju/papers#10]
Hi @aleju ,
A big thank you for the summary of the PG-Gan paper. I am trying to understand this method and your repository was really helpful!

I have a question, and I was wondering if I can get your thoughts: The paper mentions that their training is unsupervised - meaning that it was not label-conditioned. Then how come they were able to generate label-specific images for LSUN dataset? Did they train separate networks for each label or is their network a multi-class generator? 

Thanks in advance!

**Comment by aleju** [comment]
I assume they trained one network per label, which is kind of the standard for LSUN. Usually you would only get examples from a model trained on the category "bedroom" and/or one trained on "churches", but they seem to have trained one model for each category.

**Comment by prash030** [comment]
Thank you!
