### ISSUE TITLE
Literature survey regarding "Image Generation"

### ISSUE THREAD

**Issue by rmalav15** [aleju/papers#6]
Hi Alexander Jung,

First of all, a very heartily thanks for this wonderful repository. I have seen that you are very aware of current research and you also have interest in image generation/augmentation. I have gone through
[DRAW-2015](https://arxiv.org/abs/1502.04623), [LAPGAN-2015](https://arxiv.org/abs/1506.05751), and [DCGAN-2016](https://arxiv.org/abs/1511.06434). As the above mentioned works date two year back, I wanted to explore the recent studies in the same. 

I have also explored similar problem statement such as super-resolution([SRGAN](https://arxiv.org/abs/1609.04802)), and image-to-image translation([pix2pix](https://arxiv.org/abs/1611.07004),[cyclegan](https://arxiv.org/abs/1703.10593)). It would be really helpful if you can share your knowledge of this domain or similar problems to give me an idea of recent research in the same.

Thanks and Regards,
Ram

**Comment by aleju** [comment]
WGAN and WGAN-GP are pretty popular GANs. ProGAN and "High-Resolution Image Synthesis and Semantic Manipulation with Conditional GANs" generated the best (and highest resolution) images that I'm currently aware of (the latter one with some interesting control over the generated images). StackGAN++ is afaik also good, but I didn't read the paper yet. BEGAN created some beautiful images, though not necessarily with the most realistic style.
There's also a paper about Weight Normalization in GANs, which I think is in the summaries. Afaik that paper isn't too popular, but the results seemed decent to me.
There was recently a paper called "Deep Image Prior", which had some interesting results that were related to image generation. Only skimmed that paper yet though, so can't say much more to that.

**Comment by rmalav15** [comment]
Thank you, Alex.
That is all I needed. I will be benchmarking these methods soon. I am closing the issue.
Thanks Again, 
Ram
